CREATE TABLE IF NOT EXISTS `hadiths_knowledge` (
  `hadithId` int NOT NULL,
  `ref` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `book_alias` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `knowledge_model` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary_ar` text COLLATE utf8mb4_unicode_ci,
  `topics_ar` text COLLATE utf8mb4_unicode_ci,
  `teaching_ar` text COLLATE utf8mb4_unicode_ci,
  `summary_en` text COLLATE utf8mb4_unicode_ci,
  `topics_en` text COLLATE utf8mb4_unicode_ci,
  `likely_questions_en` mediumtext COLLATE utf8mb4_unicode_ci,
  `teaching_en` text COLLATE utf8mb4_unicode_ci,
  `keywords_en` text COLLATE utf8mb4_unicode_ci,
  `knowledge_json` json DEFAULT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `lastmod` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`hadithId`),
  KEY `ndx_book_alias` (`book_alias`),
  KEY `ndx_source_hash` (`source_hash`),
  CONSTRAINT `fk_hadiths_knowledge_hadith` FOREIGN KEY (`hadithId`) REFERENCES `hadiths` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
